Refactor/ben/click
LLNL/merlin-spellbook pull request #19
Opened 2021-02-25 19:54 UTC by ben-bay

Here's the click refactor (doing this first to apply to internal spellbook later).

I wish we had unit tests and cli tests to be sure I didn't break anything

2021-02-25 20:04 UTC, lucpeterson requested changes
I think we need to go through a lot of tests to see how much this breaks. Not sure how to do it, besides manually.

2021-02-25 20:04 UTC, lucpeterson commented on spellbook/commands/serialize.py
> +    type=str, # TODO nargs="+"
todo

2021-02-25 20:04 UTC, lucpeterson commented on spellbook/commands/stack-npz.py
> +    type=str,#TODO nargs="+"
todo

2021-02-25 20:07 UTC, lucpeterson commented
Since the old arg parser is there in each command, could we just compare them, running, eg
python stack_npz.py my_args
spellbook stack_npz my_args
to see if they're the same?

2021-02-25 23:12 UTC, ben-bay commented
@lucpeterson `make-samples` works the same as the original. I don't have time today to test the others, but I used the same methods across all 7 commands.

2021-02-26 17:19 UTC, lucpeterson requested changes
check that these all run. i think some bits of code were unintentionally deleted

2021-02-26 17:19 UTC, lucpeterson commented on spellbook/data_formatting/conduit/python/translator.py
> -def import_conduit():
we probably need to keep conduit

2021-02-26 17:19 UTC, lucpeterson commented on spellbook/data_formatting/serialize.py
> -def process_args(args):
probably need to keep this function

2021-03-08 15:13 UTC, merged